---
platform: linux
image: docker:///boshcpi/aws-cpi-release
inputs:
  - name: stemcell
  - name: bosh-cpi-src
  - name: bats
run:
  path: bosh-cpi-src/ci/tasks/run-bats.sh
params:
  aws_access_key_id:            replace-me
  aws_secret_access_key:        replace-me
  base_os:                      replace-me
  BAT_STEMCELL_NAME:            replace-me
  BAT_VCAP_PASSWORD:            replace-me
  public_key_name:              replace-me
  region_name:                  replace-me
  stack_name:                   replace-me
  private_key_data:             replace-me
