---
groups:
  - name: bosh-aws-cpi-release
    jobs:
      - recreate-infrastructure-primary
      - bats-ubuntu-setup-director
      - bats-ubuntu
      - bats-centos-setup-director
      - bats-centos

jobs:
  - name: recreate-infrastructure-primary
    serial_groups: [bats-centos, bats-ubuntu]
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}

      - task: check-for-running-instances
        file: bosh-cpi-src/ci/tasks/check-for-running-instances.yml
        config: &recreate-primary-config
          params:
            aws_access_key_id:        {{aws_access_key__primary}}
            aws_secret_access_key:    {{aws_secret_key__primary}}
            region_name:              {{aws_region__primary}}
            stack_name:               primary
            stack_prefix:             not-applicable

      - task: teardown-infrastructure
        file: bosh-cpi-src/ci/tasks/teardown-infrastructure.yml
        config: *recreate-primary-config

      - task: setup-infrastructure
        file: bosh-cpi-src/ci/tasks/setup-infrastructure.yml
        config: *recreate-primary-config

  - name: bats-ubuntu-setup-director
    serial_groups: [bats-ubuntu]
    plan:
      - aggregate:
        - {trigger: true,                                                   get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false,     passed: [recreate-infrastructure-primary],   get: bosh-cpi-src,     resource: bosh-cpi-src-in}
        - {trigger: false,                                                  get: bosh-init}
        - {trigger: false,                                                  get: bosh-release}
        - {trigger: false,                                                  get: stemcell, resource: aws-ubuntu-hvm-stemcell}
      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            director_password:     {{bosh_director_password}}
            director_username:     {{bosh_director_username}}
            private_key_data:      {{bosh_private_key}}
            public_key_name:       {{bosh_public_key_name}}
            region_name:           {{aws_region__primary}}
            stack_name:            primary
            stack_prefix:          Ubuntu
            use_iam:               false
            use_s3_blobstore:      false

  - name: bats-ubuntu
    serial_groups: [bats-ubuntu]
    plan:
      - aggregate:
        - {trigger: true,                              get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-ubuntu-hvm-stemcell}
        - {trigger: false,         passed: [bats-ubuntu-setup-director],                    get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-release}
        - {trigger: false,                             get: bosh-init}

      - task: run-bats
        file: bosh-cpi-src/ci/tasks/run-bats.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            base_os:               Ubuntu
            BAT_STEMCELL_NAME:     {{BAT_STEMCELL_NAME_hvm_ubuntu}}
            BAT_VCAP_PASSWORD:     {{BAT_VCAP_PASSWORD}}
            public_key_name:       {{bosh_public_key_name}}
            region_name:           {{aws_region__primary}}
            stack_name:            primary

      - task: teardown-director
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

  - name: bats-centos-setup-director
    serial_groups: [bats-centos]
    plan:
      - aggregate:
        - {trigger: true,                              get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false,     passed: [recreate-infrastructure-primary],                        get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false,                             get: bosh-release}
        - {trigger: false,                             get: stemcell, resource: aws-centos-hvm-stemcell}
      - task: setup-director
        file: bosh-cpi-src/ci/tasks/setup-director.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            director_password:     {{bosh_director_password}}
            director_username:     {{bosh_director_username}}
            private_key_data:      {{bosh_private_key}}
            public_key_name:       {{bosh_public_key_name}}
            region_name:           {{aws_region__primary}}
            stack_name:            primary
            stack_prefix:          Centos
            use_iam:               false
            use_s3_blobstore:      false

  - name: bats-centos
    serial_groups: [bats-centos]
    plan:
      - aggregate:
        - {trigger: true,                              get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts}
        - {trigger: false,                             get: stemcell, resource: aws-centos-hvm-stemcell}
        - {trigger: false,        passed: [bats-centos-setup-director],                     get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false,                             get: bosh-init}
        - {trigger: false,                             get: bats}
        - {trigger: false,                             get: bosh-release}

      - task: run-bats
        file: bosh-cpi-src/ci/tasks/run-bats.yml
        config:
          params:
            aws_access_key_id:     {{aws_access_key__primary}}
            aws_secret_access_key: {{aws_secret_key__primary}}
            base_os:               Centos
            BAT_STEMCELL_NAME:     {{BAT_STEMCELL_NAME_hvm_centos}}
            BAT_VCAP_PASSWORD:     {{BAT_VCAP_PASSWORD}}
            public_key_name:       {{bosh_public_key_name}}
            region_name:           {{aws_region__primary}}
            stack_name:            primary

      - task: teardown-director
        file: bosh-cpi-src/ci/tasks/teardown-director.yml

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-aws-cpi\.tgz
      bucket: {{aws_s3_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bosh-cpi-src-in
    type: git
    source:
      uri: https://github.com/emc-cmd/bosh-aws-cpi-release.git
      branch: master
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: {{aws_s3_bucket}}
      region_name: {{aws_region__primary}}
      access_key_id: {{aws_access_key__primary}}
      secret_access_key: {{aws_secret_key__primary}}

  - name: bats
    type: git
    source:
      uri: https://github.com/EMC-CMD/bosh-acceptance-tests.git
      branch: PR-BOSHSSH

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bosh-aws-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release

  - name: aws-ubuntu-hvm-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: aws-centos-hvm-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-centos-7-go_agent
